//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapCoreFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapCoreFluttifyPlugin (SubHandlerCustom)
- (NSDictionary<NSString*, Handler>*) getSubHandlerCustom;
@end

NS_ASSUME_NONNULL_END
