//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "BmapCoreFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface BmapCoreFluttifyPlugin (SubHandler1)
- (NSDictionary<NSString*, Handler>*) getSubHandler1;
@end

NS_ASSUME_NONNULL_END
