name: bmap_core_fluttify
description: An `BaiduMap` Core Component, Powered By `Fluttify` Engine, Which Generates Dart Binding For Native SDK.
version: 0.0.6+d0a1b9b
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/baidu_map_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttify.bmap_core_fluttify
        pluginClass: BmapCoreFluttifyPlugin
      ios:
        pluginClass: BmapCoreFluttifyPlugin