// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMK_COORD_TYPE {
  BMK_COORDTYPE_GPS,
  BMK_COORDTYPE_COMMON,
  BMK_COORDTYPE_BD09LL
}