// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_core_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_core_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class BMKIndoorPlanNode extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<BMKIndoorPlanNode> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::createBMKIndoorPlanNode');
    final object = BMKIndoorPlanNode()..refId = refId..tag = 'bmap_core_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKIndoorPlanNode>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::create_batchBMKIndoorPlanNode', {'length': length});
  
    final List<BMKIndoorPlanNode> typedResult = resultBatch.map((result) => BMKIndoorPlanNode()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_floor() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKIndoorPlanNode::get_floor", {'refId': refId});
  
    return result;
  }
  
  Future<CLLocationCoordinate2D> get_pt() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKIndoorPlanNode::get_pt", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  //endregion

  //region setters
  Future<void> set_floor(String floor) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKIndoorPlanNode::set_floor', {'refId': refId, "floor": floor});
  
  
  }
  
  Future<void> set_pt(CLLocationCoordinate2D pt) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKIndoorPlanNode::set_pt', {'refId': refId, "pt": pt.refId});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKIndoorPlanNode_Batch on List<BMKIndoorPlanNode> {
  //region getters
  Future<List<String>> get_floor_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKIndoorPlanNode::get_floor_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_pt_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKIndoorPlanNode::get_pt_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region methods
  
  //endregion
}