// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_core_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class BMKMapPoint extends NSObject  {
  //region constants
  static const String name__ = 'BMKMapPoint';

  
  //endregion

  //region creators
  static Future<BMKMapPoint> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::createBMKMapPoint');
    final object = BMKMapPoint()..refId = refId..tag__ = 'bmap_core_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKMapPoint>> create_batch__(int length) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::create_batchBMKMapPoint', {'length': length});
  
    final List<BMKMapPoint> typedResult = resultBatch.map((result) => BMKMapPoint()..refId = result..tag__ = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<double> get_x() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapPoint::get_x", {'refId': refId});
  
    return __result__;
  }
  
  Future<double> get_y() async {
    final __result__ = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapPoint::get_y", {'refId': refId});
  
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_x(double x) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapPoint::set_x', {'refId': refId, "x": x});
  
  
  }
  
  Future<void> set_y(double y) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapPoint::set_y', {'refId': refId, "y": y});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKMapPoint_Batch on List<BMKMapPoint> {
  //region getters
  Future<List<double>> get_x_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapPoint::get_x_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_y_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapPoint::get_y_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<double>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_x_batch(List<double> x) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapPoint::set_x_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "x": x[__i__]}]);
  
  
  }
  
  Future<void> set_y_batch(List<double> y) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapPoint::set_y_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "y": y[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}