// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_core_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_core_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class BMKMapSize extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<BMKMapSize> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::createBMKMapSize');
    final object = BMKMapSize()..refId = refId..tag = 'bmap_core_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKMapSize>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::create_batchBMKMapSize', {'length': length});
  
    final List<BMKMapSize> typedResult = resultBatch.map((result) => BMKMapSize()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<double> get_width() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapSize::get_width", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_height() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapSize::get_height", {'refId': refId});
  
    return result;
  }
  
  //endregion

  //region setters
  Future<void> set_width(double width) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapSize::set_width', {'refId': refId, "width": width});
  
  
  }
  
  Future<void> set_height(double height) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKMapSize::set_height', {'refId': refId, "height": height});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKMapSize_Batch on List<BMKMapSize> {
  //region getters
  Future<List<double>> get_width_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapSize::get_width_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_height_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKMapSize::get_height_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  //endregion

  //region methods
  
  //endregion
}