// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKOpenErrorCode {
  BMK_OPEN_NO_ERROR,
  BMK_OPEN_WEB_MAP,
  BMK_OPEN_OPTION_NULL,
  BMK_OPEN_NOT_SUPPORT,
  BMK_OPEN_POI_DETAIL_UID_NULL,
  BMK_OPEN_POI_NEARBY_KEYWORD_NULL,
  BMK_OPEN_ROUTE_START_ERROR,
  BMK_OPEN_ROUTE_END_ERROR,
  BMK_OPEN_PANORAMA_UID_ERROR,
  BMK_OPEN_PANORAMA_ABSENT,
  BMK_OPEN_PERMISSION_UNFINISHED,
  BMK_OPEN_KEY_ERROR,
  BMK_OPEN_NETWOKR_ERROR
}