// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKOpenErrorCode {
  BMK_OPEN_NO_ERROR /* 0 */,
  BMK_OPEN_WEB_MAP /* 0 */,
  BMK_OPEN_OPTION_NULL /* 0 */,
  BMK_OPEN_NOT_SUPPORT /* 0 */,
  BMK_OPEN_POI_DETAIL_UID_NULL /* 0 */,
  BMK_OPEN_POI_NEARBY_KEYWORD_NULL /* 0 */,
  BMK_OPEN_ROUTE_START_ERROR /* 0 */,
  BMK_OPEN_ROUTE_END_ERROR /* 0 */,
  BMK_OPEN_PANORAMA_UID_ERROR /* 0 */,
  BMK_OPEN_PANORAMA_ABSENT /* 0 */,
  BMK_OPEN_PERMISSION_UNFINISHED /* 0 */,
  BMK_OPEN_KEY_ERROR /* 0 */,
  BMK_OPEN_NETWOKR_ERROR /* 0 */
}