// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKPermissionCheckResultCode {
  E_PERMISSIONCHECK_CONNECT_ERROR,
  E_PERMISSIONCHECK_DATA_ERROR,
  E_PERMISSIONCHECK_OK,
  E_PERMISSIONCHECK_KEY_ERROR,
  E_PERMISSIONCHECK_MCODE_ERROR,
  E_PERMISSIONCHECK_UID_KEY_ERROR,
  E_PERMISSIONCHECK_KEY_FORBIDEN,
  E_PERMISSIONCHECK_KEY_DENY_BY_SERVER,
  E_PERMISSIONCHECK_USER_DENY_BY_SERVER
}