// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_core_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_core_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class BMKPlanNode extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<BMKPlanNode> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::createBMKPlanNode');
    final object = BMKPlanNode()..refId = refId..tag = 'bmap_core_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKPlanNode>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::create_batchBMKPlanNode', {'length': length});
  
    final List<BMKPlanNode> typedResult = resultBatch.map((result) => BMKPlanNode()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<double> get_latitudeDelta() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_latitudeDelta", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_longitudeDelta() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_longitudeDelta", {'refId': refId});
  
    return result;
  }
  
  Future<CLLocationCoordinate2D> get_northEast() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_northEast", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  Future<CLLocationCoordinate2D> get_southWest() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_southWest", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  Future<CLLocationCoordinate2D> get_center() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_center", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  Future<int> get_latitudeE6() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_latitudeE6", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_longitudeE6() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_longitudeE6", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_x() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_x", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_y() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_y", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_width() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_width", {'refId': refId});
  
    return result;
  }
  
  Future<double> get_height() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_height", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_cityName() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_cityName", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_cityID() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_cityID", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_name() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_name", {'refId': refId});
  
    return result;
  }
  
  Future<CLLocationCoordinate2D> get_pt() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_pt", {'refId': refId});
    kNativeObjectPool.add(CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  //endregion

  //region setters
  Future<void> set_latitudeDelta(double latitudeDelta) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_latitudeDelta', {'refId': refId, "latitudeDelta": latitudeDelta});
  
  
  }
  
  Future<void> set_longitudeDelta(double longitudeDelta) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_longitudeDelta', {'refId': refId, "longitudeDelta": longitudeDelta});
  
  
  }
  
  Future<void> set_northEast(CLLocationCoordinate2D northEast) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_northEast', {'refId': refId, "northEast": northEast.refId});
  
  
  }
  
  Future<void> set_southWest(CLLocationCoordinate2D southWest) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_southWest', {'refId': refId, "southWest": southWest.refId});
  
  
  }
  
  Future<void> set_center(CLLocationCoordinate2D center) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_center', {'refId': refId, "center": center.refId});
  
  
  }
  
  Future<void> set_latitudeE6(int latitudeE6) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_latitudeE6', {'refId': refId, "latitudeE6": latitudeE6});
  
  
  }
  
  Future<void> set_longitudeE6(int longitudeE6) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_longitudeE6', {'refId': refId, "longitudeE6": longitudeE6});
  
  
  }
  
  Future<void> set_x(double x) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_x', {'refId': refId, "x": x});
  
  
  }
  
  Future<void> set_y(double y) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_y', {'refId': refId, "y": y});
  
  
  }
  
  Future<void> set_width(double width) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_width', {'refId': refId, "width": width});
  
  
  }
  
  Future<void> set_height(double height) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('::set_height', {'refId': refId, "height": height});
  
  
  }
  
  Future<void> set_cityName(String cityName) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKPlanNode::set_cityName', {'refId': refId, "cityName": cityName});
  
  
  }
  
  Future<void> set_cityID(int cityID) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKPlanNode::set_cityID', {'refId': refId, "cityID": cityID});
  
  
  }
  
  Future<void> set_name(String name) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKPlanNode::set_name', {'refId': refId, "name": name});
  
  
  }
  
  Future<void> set_pt(CLLocationCoordinate2D pt) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKPlanNode::set_pt', {'refId': refId, "pt": pt.refId});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKPlanNode_Batch on List<BMKPlanNode> {
  //region getters
  Future<List<double>> get_latitudeDelta_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_latitudeDelta_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_longitudeDelta_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_longitudeDelta_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_northEast_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_northEast_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_southWest_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_southWest_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_center_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_center_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<int>> get_latitudeE6_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_latitudeE6_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_longitudeE6_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_longitudeE6_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_x_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_x_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_y_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_y_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_width_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_width_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<double>> get_height_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("::get_height_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_cityName_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_cityName_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_cityID_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_cityID_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_name_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_name_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<CLLocationCoordinate2D>> get_pt_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKPlanNode::get_pt_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocationCoordinate2D()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region methods
  
  //endregion
}