// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum BMKSearchErrorCode {
  BMK_SEARCH_NO_ERROR /* 0 */,
  BMK_SEARCH_AMBIGUOUS_KEYWORD /* 0 */,
  BMK_SEARCH_AMBIGUOUS_ROURE_ADDR /* 0 */,
  BMK_SEARCH_NOT_SUPPORT_BUS /* 0 */,
  BMK_SEARCH_NOT_SUPPORT_BUS_2CITY /* 0 */,
  BMK_SEARCH_RESULT_NOT_FOUND /* 0 */,
  BMK_SEARCH_ST_EN_TOO_NEAR /* 0 */,
  BMK_SEARCH_KEY_ERROR /* 0 */,
  BMK_SEARCH_NETWOKR_ERROR /* 0 */,
  BMK_SEARCH_NETWOKR_TIMEOUT /* 0 */,
  BMK_SEARCH_PERMISSION_UNFINISHED /* 0 */,
  BMK_SEARCH_INDOOR_ID_ERROR /* 0 */,
  BMK_SEARCH_FLOOR_ERROR /* 0 */,
  BMK_SEARCH_INDOOR_ROUTE_NO_IN_BUILDING /* 0 */,
  BMK_SEARCH_INDOOR_ROUTE_NO_IN_SAME_BUILDING /* 0 */,
  BMK_SEARCH_PARAMETER_ERROR /* 0 */,
  BMK_SEARCH_SERVER_ERROR /* 0 */
}