// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:bmap_core_fluttify/src/ios/ios.export.g.dart';
import 'package:bmap_core_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class BMKUserLocation extends NSObject  {
  //region constants
  
  //endregion

  //region creators
  static Future<BMKUserLocation> create__() async {
    final int refId = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::createBMKUserLocation');
    final object = BMKUserLocation()..refId = refId..tag = 'bmap_core_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<BMKUserLocation>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('ObjectFactory::create_batchBMKUserLocation', {'length': length});
  
    final List<BMKUserLocation> typedResult = resultBatch.map((result) => BMKUserLocation()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<bool> get_updating() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_isUpdating", {'refId': refId});
  
    return result;
  }
  
  Future<CLLocation> get_location() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_location", {'refId': refId});
    kNativeObjectPool.add(CLLocation()..refId = result..tag = 'bmap_core_fluttify');
    return CLLocation()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  Future<CLHeading> get_heading() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_heading", {'refId': refId});
    kNativeObjectPool.add(CLHeading()..refId = result..tag = 'bmap_core_fluttify');
    return CLHeading()..refId = result..tag = 'bmap_core_fluttify';
  }
  
  Future<String> get_title() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_title", {'refId': refId});
  
    return result;
  }
  
  Future<String> get_subtitle() async {
    final result = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_subtitle", {'refId': refId});
  
    return result;
  }
  
  //endregion

  //region setters
  Future<void> set_updating(bool updating) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKUserLocation::set_updating', {'refId': refId, "updating": updating});
  
  
  }
  
  Future<void> set_location(CLLocation location) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKUserLocation::set_location', {'refId': refId, "location": location.refId});
  
  
  }
  
  Future<void> set_heading(CLHeading heading) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKUserLocation::set_heading', {'refId': refId, "heading": heading.refId});
  
  
  }
  
  Future<void> set_title(String title) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKUserLocation::set_title', {'refId': refId, "title": title});
  
  
  }
  
  Future<void> set_subtitle(String subtitle) async {
    await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod('BMKUserLocation::set_subtitle', {'refId': refId, "subtitle": subtitle});
  
  
  }
  
  //endregion

  //region methods
  
  //endregion
}

extension BMKUserLocation_Batch on List<BMKUserLocation> {
  //region getters
  Future<List<bool>> get_updating_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_isUpdating_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<CLLocation>> get_location_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_location_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLLocation()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<CLHeading>> get_heading_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_heading_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => CLHeading()..refId = result..tag = 'bmap_core_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  Future<List<String>> get_title_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_title_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_subtitle_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/bmap_core_fluttify').invokeMethod("BMKUserLocation::get_subtitle_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  //endregion

  //region methods
  
  //endregion
}